/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.chess.UI;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Insets;

/**
 *
 * @author MSalop
 */
public class Board extends javax.swing.JFrame {

    /**
     * Creates new form Board
     */
    public Board() {
        initComponents();
    }
    
    @Override
    public void paint(Graphics graphics) {
        
        int frameWidth = getWidth();
        int frameHeight = getHeight();
        Insets insets = getInsets();
        int width = frameWidth - insets.left - insets.right;
        int height = frameHeight - insets.top - insets.bottom;
        int size = Math.min( width, height );
        size = size - size % 8;
        int square = size / 8;
        int x = insets.left + ( width - size ) / 2;
        int y = insets.top + ( height - size ) / 2;
        
        graphics.clearRect(0, 0, frameWidth, frameHeight);
        
        graphics.setColor( new Color( 100, 200, 200 ) );
        graphics.fillRect(x, y, size, size);
        
        graphics.setColor( new Color( 50, 100, 100 ) );
        
        int i = 0;
        int j = 0;
        while ( j < 8 ) {
            
            if ( ( i + j ) % 2 == 1 ) graphics.fillRect( x + i*square, y + j*square, square, square );
            
            if ( 8 <= ++i ) { j++; i = 0; }
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
